### PR TITLE
Add automatic database migrations to startup

### PR DESCRIPTION
**Pull request by zbuc**
Database migrations will automatically be run.
Name them according to the format (`#_YYYY-MM-DD-descriptive_name.sql`)
and put in the appropriate directory and it will run on the next server
startup.

Migrations are only run once, in ascending numeric order. The current
database state is tracked in a new database called `Global`.

This simplifies server setup: now the only step is to create the four
databases. The base SQL and migrations will be run automatically from
that point on.

This also simplifies migrations, which will no longer need to
incorporate complex conditional logic in order to be repeatable.

### CODE REVIEW

**Comment by zbuc** [comment]
I'm not a C# guy and there are some stylistic things I don't like, mainly calling out to `DatabaseManager.Global` in the main `Database` class is very hacky, as is what I had to do with the `Global` prepared statements.

But, it all works and I think is good for a first pass.

**Comment by zbuc** [comment]
Fixes #20

**Comment by zbuc** [comment]
I cleaned up and simplified some of the code, and rebased against `master`.

All current migrations run and the database is in a working state after compiling and running off this branch.

**Comment by Forbiddenz** [comment]
This is s great idea but I do wonder if this entire process should be separated into its own project in the solution.  I.e. Patcher because this is not really a server process but more so a patcher / installer issue

**Comment by Mag-nus** [comment]
I'm not fond of the complexity for this. What i'd like to see instead is us merge our updates down into the base sql file at some point, and, in the future, when new updates are added, also update the base sql file as well, so a new install wouldn't need to apply the updates, as they'd be.. up to date. (i'm by no means a db person so i don't know if this is against the norm)

**Comment by Forbiddenz** [comment]
Hi Mag-nus,
The problem with your idea is some asshat will figure out how to screw up their original db.

I worked on many production level database patches and they pretty much all start at step x and move forward where x can be the current software version.

Your right as a new installer needs to run from version 0 and then if version 50 removes a table in version 0 it will be a useless step and take more time.

But the benefits of the system far outweigh the useless garbage.

With a design that goes by version and up you can guarantee that the database is always standard and it eliminates the room for error with things getting out of sync or even missed.

When you have the step process it's a little more work and sometimes seems dumb but it keeps all the db updates on a forward track even if they seem to be doing things the slow way.

**Pull request closed without merging**
