### PR TITLE
fixing oak salvage

### PR DESCRIPTION
**Pull request by gmriggs**

### CODE REVIEW

**Comment by dirtyelf** [comment]
Doesn't it also need to be applied to missile weapons? Is that taken care of somewhere else?

**Comment by gmriggs** [comment]
Can you link an example of a Missile Weapon with a speed?

**Comment by gmriggs** [comment]
you are correct, missile weapons do indeed have a speed

for some reason, the /ci yumi that i examined did not have a speed shown in appraisal, even though it appears to have a speed in the data

in addition to this, i don't think any ace code is actually evaluating the speed of missile weapons yet...

**Comment by dirtyelf** [comment]
missile wep speed is used for the reload animation

**Comment by gmriggs** [comment]
is it used for the 'launch arrow' animation + the reload animation, or just the reload anim?

**Pull request merged**
