### PR TITLE
Save Item to DB in TryCreateInInventoryWithNetworking

### PR DESCRIPTION
**Pull request by LtRipley36706**
Attempt at preventing item rollback on crashes

### CODE REVIEW

**Comment by Mag-nus** [comment]
Please make this server configurable, default to off.

**Comment by LtRipley36706** [comment]
CE running this has no impact on perf.

**Comment by Mag-nus** [comment]
Both the rx and tx saves should be conditional based on the bool property gmriggs mentioned.

That will keep the system 1:1 in both configurations and still optional.

**Comment by LtRipley36706** [comment]
I actually disagree with the optional nature you propose. The purpose of the save is to prevent issues relating to crashes which can't always be prevented/anticipated, where as throughout the code SaveBiotaToDatabase is used to force saves to ensure states are preserved, and not optionally, just for such occasions. 

player_receive_immediate_save was added at some point and actually is more expensive because its doing a full player save instead of just the item saves needed in current use cases. The PR code actually negates the need to save entire players because on both outgoing and incoming items, the item with significantly less properties/dictionaries is saved vs the three instances of this code:
```cs
if (PropertyManager.GetBool("player_receive_immediate_save").Item)
                                player.RushNextPlayerSave(5);
```

**Comment by Mag-nus** [comment]
A server operator should be able to chose if they want to incur the additional overhead with ACID-like behavior, or, are ok with a rollback of approx 0-5m (which is similar to how retail operated)

**Comment by LtRipley36706** [comment]
this isn't a rollback. The item is lost to the void because of the nature of saves. It saved in the item with null owner/container because that save is "required" and then subsequently lost because the update to add owner/container is no longer required? a true rollback is better because the previous full state is preserved, given that isn't the case here, you can't say its an acceptable outcome

**Comment by Mag-nus** [comment]
The concern here is player to player/chest item transfers right? If so, we can solve this in a much more database-efficient manner.

**Comment by LtRipley36706** [comment]
concern here is player to player, player to npc, npc to player, player to container, container to player

**Comment by Mag-nus** [comment]
If you comment out the save on RemoveItemFromContainer, what issues remain that need to be solved?

Here is the reason why I originally added that:

Notes:
Landblocks are each on their own independent 5m save intervals
Players all have their own independent 5m save intervals

Bob is saved
Bob gives sword to Jim
Bob is saved
Server crashes, Jim was not saved.

The sword is still recorded as being possessed by Bob. When Bob relogs, what happens if his inventory is full? Any excess items should be moved into any available slot, or, dropped on the ground. I don't believe this logic is implemented.

Currently, as implemented, if items are being saved without containers while they are being transitioned between containers, that's a problem that we should fix.

We shouldn't then be saving the item again after it's received by the container to bring the item back out of the void.

**Pull request merged**
