### PR TITLE
[WIP -Debug] debugging bad weenie scrolls

### PR DESCRIPTION
**Pull request by harliq**
For catching bad scrolls/weenies

### CODE REVIEW

**Comment by gmriggs** [comment]
I forwarded this particular error to @Mag-nus, so that he can investigate the best place to insert such error handling and logging code

I think perhaps the inner database lookup code should just be returning null properly / not crashing there, and then it would maybe be the responsibility of the outer game code that fetches the weenie to check if null / handle / error logging

**Comment by harliq** [comment]
I agree, this just for DnF at the moment for helping find issues in their stuff.  Not really meant for master

**Comment by Mag-nus** [comment]
I don't think this is correct.

I believe adapter was working correctly. The null check should be going higher up in the chain, or somewhere else.

**Comment by harliq** [comment]
no need for this PR, closing

**Comment by harliq** [comment]
close

**Pull request closed without merging**
