### PR TITLE
Null mana c

### PR DESCRIPTION
**Pull request by harliq**
Nulling ManaC for appraisal

### CODE REVIEW

**Comment by Warloxx01** [comment]
Hi, I added this and the (mana conversion mod tweaks) to a clean server build and this happened when I was playing in Metos...

[Error.txt](https://github.com/ACEmulator/ACE/files/3923081/Error.txt)

This didnt crash my server.

**Comment by gmriggs** [comment]
The crash @Warloxx01 was seeing was from the other PR

**Comment by Warloxx01** [comment]
Thanks, Helped me understand.

**Comment by harliq** [comment]
No longer needed

**Pull request closed without merging**
