### PR TITLE
prototype: adding account-wide house recall / permissions

### PR DESCRIPTION
**Pull request by gmriggs**
needs more research into 'roommates' structure next...

### CODE REVIEW

**Comment by Warloxx01** [comment]
I have been playing around with this and found it to work as it should. I only have had 1 issue and i can not say it was this addition that caused it. A secondary character on the main account ( not the actual cottage owner) recalled back to the cottage and landed in complete darkness. Iwas unable to correct this, I had to restart the server to correct the issue. Im not sure if this was a result of this update (maybe read the landing coords wrong?) or what but out of maybe 60 or 70 recalls from different locations in Dereth with that character that was the only issue I had and it only happened once.

**Comment by gmriggs** [comment]
if your can repro the black screen, can you post of a /loc of it?

**Comment by Warloxx01** [comment]
@gmriggs Sure, I can give you the loc no problem, but im not sure I can repo the Black screen, as I said it only happened once. out of quit a few recalls. I can get the loc though no problem.

Home owner recall /loc
Your location is: 0xA6CB0036 [150.270996 129.328995 54.005001] 0.999852 0.000000 0.000000 0.017215

Secondary character recall /loc
Your location is: 0xA6CB0036 [150.270996 129.328995 54.005001] 0.999852 0.000000 0.000000 0.017215


They appear to be identical. Like I said it may not have been an issue with this update.

**Comment by Warloxx01** [comment]
I do have one question, were the other characters on the same account that the house owner on able to turn the house hooks on/off I can't seem to remember?

**Comment by Warloxx01** [comment]
Found my answer...
https://asheron.fandom.com/wiki/Housing_FAQ


Storage for other characters

Q. What do my other characters do for storage?
A. All characters on the account share the house and can access its storage space, hooks and all housing commands (except @house abandon and commands to change allegiance permissions).

**Comment by Warloxx01** [comment]
My other character can't turn on or off the hooks, and I have not tried ANY of the other commands so far.

**Comment by gmriggs** [comment]
Hey Warloxx,

Returning to this PR to give it the proper treatment. This PR was only a preliminary version, to give players the ability to /hr from other characters on the account.

This PR will be continued further to include the full features for account-wide housing

**Pull request merged**
