### PR TITLE
verifying spell ids in loot tables

### PR DESCRIPTION
**Pull request by gmriggs**
GemCreatureSpellMatrix:

AxeMasterySelf1[6]: (2275) MaceMasterySelf7 =&gt; (2203) - AxeMasterySelf7
BowMasterySelf1[6]: (2243) ImpregnabilitySelf7 =&gt; (2207) - BowMasterySelf7
DeceptionMasterySelf1[6]: (2226) DeceptionMasteryOther7 =&gt; (2227) - DeceptionMasterySelf7
JumpingMasterySelf1[6]: (2256) JumpingMasteryOther7 =&gt; (2257) - JumpingMasterySelf7
RecklessnessMasterySelf1[5]: (5831) RecklessnessMasterySelf5 =&gt; (5832) - RecklessnessMasterySelf6
ShieldMasterySelf1[0]: (5843) ShieldMasteryOther1 =&gt; (5851) - ShieldMasterySelf1
ShieldMasterySelf1[1]: (5844) ShieldMasteryOther2 =&gt; (5852) - ShieldMasterySelf2
ShieldMasterySelf1[2]: (5845) ShieldMasteryOther3 =&gt; (5853) - ShieldMasterySelf3
ShieldMasterySelf1[3]: (5846) ShieldMasteryOther4 =&gt; (5854) - ShieldMasterySelf4
ShieldMasterySelf1[4]: (5847) ShieldMasteryOther5 =&gt; (5855) - ShieldMasterySelf5
ShieldMasterySelf1[5]: (5848) ShieldMasteryOther6 =&gt; (5856) - ShieldMasterySelf6
SneakAttackMasterySelf1[0]: (5867) SneakAttackMasteryOther1 =&gt; (5875) - SneakAttackMasterySelf1
SneakAttackMasterySelf1[1]: (5868) SneakAttackMasteryOther2 =&gt; (5876) - SneakAttackMasterySelf2
SneakAttackMasterySelf1[2]: (5869) SneakAttackMasteryOther3 =&gt; (5877) - SneakAttackMasterySelf3
SneakAttackMasterySelf1[3]: (5870) SneakAttackMasteryOther4 =&gt; (5878) - SneakAttackMasterySelf4
SneakAttackMasterySelf1[4]: (5871) SneakAttackMasteryOther5 =&gt; (5879) - SneakAttackMasterySelf5
SneakAttackMasterySelf1[5]: (5872) SneakAttackMasteryOther6 =&gt; (5880) - SneakAttackMasterySelf6
TwoHandedMasterySelf1[0]: (346) MaceMasterySelf1 =&gt; (5099) - TwoHandedMasterySelf1
TwoHandedMasterySelf1[1]: (347) MaceMasterySelf2 =&gt; (5100) - TwoHandedMasterySelf2
TwoHandedMasterySelf1[2]: (348) MaceMasterySelf3 =&gt; (5101) - TwoHandedMasterySelf3
TwoHandedMasterySelf1[3]: (349) MaceMasterySelf4 =&gt; (5102) - TwoHandedMasterySelf4
TwoHandedMasterySelf1[4]: (350) MaceMasterySelf5 =&gt; (5103) - TwoHandedMasterySelf5
TwoHandedMasterySelf1[5]: (351) MaceMasterySelf6 =&gt; (5104) - TwoHandedMasterySelf6
VoidMagicMasterySelf1[0]: (null) =&gt; (5411) - VoidMagicMasterySelf1
VoidMagicMasterySelf1[1]: (null) =&gt; (5412) - VoidMagicMasterySelf2
VoidMagicMasterySelf1[2]: (null) =&gt; (5413) - VoidMagicMasterySelf3
VoidMagicMasterySelf1[3]: (null) =&gt; (5414) - VoidMagicMasterySelf4
VoidMagicMasterySelf1[4]: (null) =&gt; (5415) - VoidMagicMasterySelf5
VoidMagicMasterySelf1[5]: (null) =&gt; (5416) - VoidMagicMasterySelf6
ArcanumSalvagingSelf1[0]: (null) =&gt; (3499) - ArcanumSalvagingSelf1
ArcanumSalvagingSelf1[1]: (null) =&gt; (3500) - ArcanumSalvagingSelf2
ArcanumSalvagingSelf1[2]: (null) =&gt; (3501) - ArcanumSalvagingSelf3
ArcanumSalvagingSelf1[3]: (null) =&gt; (3502) - ArcanumSalvagingSelf4
ArcanumSalvagingSelf1[4]: (null) =&gt; (3503) - ArcanumSalvagingSelf5
ArcanumSalvagingSelf1[5]: (null) =&gt; (3504) - ArcanumSalvagingSelf6
ArcanumSalvagingSelf1[6]: (3519) NuhmudirasWisdom7 =&gt; (3505) - ArcanumSalvagingSelf7
ArcanumSalvagingSelf1[7]: (4502) NuhmudirasWisdomOther8 =&gt; (4499) - ArcanumSalvagingSelf8

GemLifeSpellMatrix:

RejuvenationSelf1[3]: (190) RejuvenationSelf3 =&gt; (191) - RejuvenationSelf4
RejuvenationSelf1[4]: (190) RejuvenationSelf3 =&gt; (192) - RejuvenationSelf5
RejuvenationSelf1[5]: (190) RejuvenationSelf3 =&gt; (193) - RejuvenationSelf6

ScrollSpells:

AxeMasterySelf1[6]: (2275) MaceMasterySelf7 =&gt; (2203) - AxeMasterySelf7
AxeMasteryOther1[6]: (2274) MaceMasteryOther7 =&gt; (2202) - AxeMasteryOther7
LeadershipMasterySelf1[6]: (2262) LeadershipMasteryOther7 =&gt; (2263) - LeadershipMasterySelf7
LeadershipMasteryOther1[6]: (2263) LeadershipMasterySelf7 =&gt; (2262) - LeadershipMasteryOther7
SprintSelf1[5]: (986) SprintSelf5 =&gt; (987) - SprintSelf6
LeadenFeetOther1[2]: (1001) LeadenFeetOther2 =&gt; (1002) - LeadenFeetOther3
RejuvenationOther1[2]: (184) RejuvenationOther2 =&gt; (185) - RejuvenationOther3

ArmorSpells:

ImpregnabilitySelf1[7]: (4522) BowMasterySelf8 =&gt; (4558) - ImpregnabilitySelf8
SneakAttackMasterySelf1[0]: (5867) SneakAttackMasteryOther1 =&gt; (5875) - SneakAttackMasterySelf1
SneakAttackMasterySelf1[1]: (5868) SneakAttackMasteryOther2 =&gt; (5876) - SneakAttackMasterySelf2
SneakAttackMasterySelf1[2]: (5869) SneakAttackMasteryOther3 =&gt; (5877) - SneakAttackMasterySelf3
SneakAttackMasterySelf1[3]: (5870) SneakAttackMasteryOther4 =&gt; (5878) - SneakAttackMasterySelf4
SneakAttackMasterySelf1[4]: (5871) SneakAttackMasteryOther5 =&gt; (5879) - SneakAttackMasterySelf5
SneakAttackMasterySelf1[5]: (5872) SneakAttackMasteryOther6 =&gt; (5880) - SneakAttackMasterySelf6
DeceptionMasterySelf1[6]: (2226) DeceptionMasteryOther7 =&gt; (2227) - DeceptionMasterySelf7
AxeMasterySelf1[6]: (2275) MaceMasterySelf7 =&gt; (2203) - AxeMasterySelf7
BowMasterySelf1[6]: (2243) ImpregnabilitySelf7 =&gt; (2207) - BowMasterySelf7
ShieldMasterySelf1[0]: (5843) ShieldMasteryOther1 =&gt; (5851) - ShieldMasterySelf1
ShieldMasterySelf1[1]: (5844) ShieldMasteryOther2 =&gt; (5852) - ShieldMasterySelf2
ShieldMasterySelf1[2]: (5845) ShieldMasteryOther3 =&gt; (5853) - ShieldMasterySelf3
ShieldMasterySelf1[3]: (5846) ShieldMasteryOther4 =&gt; (5854) - ShieldMasterySelf4
ShieldMasterySelf1[4]: (5847) ShieldMasteryOther5 =&gt; (5855) - ShieldMasterySelf5
ShieldMasterySelf1[5]: (5848) ShieldMasteryOther6 =&gt; (5856) - ShieldMasterySelf6
ArcanumSalvagingSelf1[6]: (3519) NuhmudirasWisdom7 =&gt; (3505) - ArcanumSalvagingSelf7
ArcanumSalvagingSelf1[7]: (4502) NuhmudirasWisdomOther8 =&gt; (4499) - ArcanumSalvagingSelf8
LeadershipMasterySelf1[6]: (2271) LockpickMasterySelf7 =&gt; (2263) - LeadershipMasterySelf7
LeadershipMasterySelf1[7]: (4586) LockpickMasterySelf8 =&gt; (4578) - LeadershipMasterySelf8
JumpingMasterySelf1[6]: (2256) JumpingMasteryOther7 =&gt; (2257) - JumpingMasterySelf7
SprintSelf1[5]: (986) SprintSelf5 =&gt; (987) - SprintSelf6

WandSpells:

SneakAttackMasterySelf1[0]: (5867) SneakAttackMasteryOther1 =&gt; (5875) - SneakAttackMasterySelf1
SneakAttackMasterySelf1[1]: (5868) SneakAttackMasteryOther2 =&gt; (5876) - SneakAttackMasterySelf2
SneakAttackMasterySelf1[2]: (5869) SneakAttackMasteryOther3 =&gt; (5877) - SneakAttackMasterySelf3
SneakAttackMasterySelf1[3]: (5870) SneakAttackMasteryOther4 =&gt; (5878) - SneakAttackMasterySelf4
SneakAttackMasterySelf1[4]: (5871) SneakAttackMasteryOther5 =&gt; (5879) - SneakAttackMasterySelf5
SneakAttackMasterySelf1[5]: (5872) SneakAttackMasteryOther6 =&gt; (5880) - SneakAttackMasterySelf6
WarMagicMasterySelf1[6]: (2287) ManaMasterySelf7 =&gt; (2323) - WarMagicMasterySelf7
WarMagicMasterySelf1[7]: (4602) ManaMasterySelf8 =&gt; (4638) - WarMagicMasterySelf8

JewelrySpells:

ImpregnabilitySelf1[7]: (4522) BowMasterySelf8 =&gt; (4558) - ImpregnabilitySelf8
SneakAttackMasterySelf1[0]: (5867) SneakAttackMasteryOther1 =&gt; (5875) - SneakAttackMasterySelf1
SneakAttackMasterySelf1[1]: (5868) SneakAttackMasteryOther2 =&gt; (5876) - SneakAttackMasterySelf2
SneakAttackMasterySelf1[2]: (5869) SneakAttackMasteryOther3 =&gt; (5877) - SneakAttackMasterySelf3
SneakAttackMasterySelf1[3]: (5870) SneakAttackMasteryOther4 =&gt; (5878) - SneakAttackMasterySelf4
SneakAttackMasterySelf1[4]: (5871) SneakAttackMasteryOther5 =&gt; (5879) - SneakAttackMasterySelf5
SneakAttackMasterySelf1[5]: (5872) SneakAttackMasteryOther6 =&gt; (5880) - SneakAttackMasterySelf6
DeceptionMasterySelf1[6]: (2226) DeceptionMasteryOther7 =&gt; (2227) - DeceptionMasterySelf7
AxeMasterySelf1[6]: (2275) MaceMasterySelf7 =&gt; (2203) - AxeMasterySelf7
BowMasterySelf1[6]: (2243) ImpregnabilitySelf7 =&gt; (2207) - BowMasterySelf7
ShieldMasterySelf1[0]: (5843) ShieldMasteryOther1 =&gt; (5851) - ShieldMasterySelf1
ShieldMasterySelf1[1]: (5844) ShieldMasteryOther2 =&gt; (5852) - ShieldMasterySelf2
ShieldMasterySelf1[2]: (5845) ShieldMasteryOther3 =&gt; (5853) - ShieldMasterySelf3
ShieldMasterySelf1[3]: (5846) ShieldMasteryOther4 =&gt; (5854) - ShieldMasterySelf4
ShieldMasterySelf1[4]: (5847) ShieldMasteryOther5 =&gt; (5855) - ShieldMasterySelf5
ShieldMasterySelf1[5]: (5848) ShieldMasteryOther6 =&gt; (5856) - ShieldMasterySelf6
ArcanumSalvagingSelf1[6]: (3519) NuhmudirasWisdom7 =&gt; (3505) - ArcanumSalvagingSelf7
ArcanumSalvagingSelf1[7]: (4502) NuhmudirasWisdomOther8 =&gt; (4499) - ArcanumSalvagingSelf8
LeadershipMasterySelf1[6]: (2271) LockpickMasterySelf7 =&gt; (2263) - LeadershipMasterySelf7
LeadershipMasterySelf1[7]: (4586) LockpickMasterySelf8 =&gt; (4578) - LeadershipMasterySelf8
JumpingMasterySelf1[6]: (2256) JumpingMasteryOther7 =&gt; (2257) - JumpingMasterySelf7
SprintSelf1[5]: (986) SprintSelf5 =&gt; (987) - SprintSelf6

GemSpells:

AxeMasterySelf1[6]: (2275) MaceMasterySelf7 =&gt; (2203) - AxeMasterySelf7
BowMasterySelf1[6]: (2243) ImpregnabilitySelf7 =&gt; (2207) - BowMasterySelf7
DeceptionMasterySelf1[6]: (2226) DeceptionMasteryOther7 =&gt; (2227) - DeceptionMasterySelf7
LeadershipMasterySelf1[6]: (2271) LockpickMasterySelf7 =&gt; (2263) - LeadershipMasterySelf7
LeadershipMasterySelf1[7]: (4586) LockpickMasterySelf8 =&gt; (4578) - LeadershipMasterySelf8
JumpingMasterySelf1[6]: (2256) JumpingMasteryOther7 =&gt; (2257) - JumpingMasterySelf7
SprintSelf1[5]: (986) SprintSelf5 =&gt; (987) - SprintSelf6
ShieldMasterySelf1[0]: (5843) ShieldMasteryOther1 =&gt; (5851) - ShieldMasterySelf1
ShieldMasterySelf1[1]: (5844) ShieldMasteryOther2 =&gt; (5852) - ShieldMasterySelf2
ShieldMasterySelf1[2]: (5845) ShieldMasteryOther3 =&gt; (5853) - ShieldMasterySelf3
ShieldMasterySelf1[3]: (5846) ShieldMasteryOther4 =&gt; (5854) - ShieldMasterySelf4
ShieldMasterySelf1[4]: (5847) ShieldMasteryOther5 =&gt; (5855) - ShieldMasterySelf5
ShieldMasterySelf1[5]: (5848) ShieldMasteryOther6 =&gt; (5856) - ShieldMasterySelf6
SneakAttackMasterySelf1[0]: (5867) SneakAttackMasteryOther1 =&gt; (5875) - SneakAttackMasterySelf1
SneakAttackMasterySelf1[1]: (5868) SneakAttackMasteryOther2 =&gt; (5876) - SneakAttackMasterySelf2
SneakAttackMasterySelf1[2]: (5869) SneakAttackMasteryOther3 =&gt; (5877) - SneakAttackMasterySelf3
SneakAttackMasterySelf1[3]: (5870) SneakAttackMasteryOther4 =&gt; (5878) - SneakAttackMasterySelf4
SneakAttackMasterySelf1[4]: (5871) SneakAttackMasteryOther5 =&gt; (5879) - SneakAttackMasterySelf5
SneakAttackMasterySelf1[5]: (5872) SneakAttackMasteryOther6 =&gt; (5880) - SneakAttackMasterySelf6
ArcanumSalvagingSelf1[6]: (3519) NuhmudirasWisdom7 =&gt; (3505) - ArcanumSalvagingSelf7
ArcanumSalvagingSelf1[7]: (4502) NuhmudirasWisdomOther8 =&gt; (4499) - ArcanumSalvagingSelf8

MeleeSpells:

SneakAttackMasterySelf1[0]: (5867) SneakAttackMasteryOther1 =&gt; (5875) - SneakAttackMasterySelf1
SneakAttackMasterySelf1[1]: (5868) SneakAttackMasteryOther2 =&gt; (5876) - SneakAttackMasterySelf2
SneakAttackMasterySelf1[2]: (5869) SneakAttackMasteryOther3 =&gt; (5877) - SneakAttackMasterySelf3
SneakAttackMasterySelf1[3]: (5870) SneakAttackMasteryOther4 =&gt; (5878) - SneakAttackMasterySelf4
SneakAttackMasterySelf1[4]: (5871) SneakAttackMasteryOther5 =&gt; (5879) - SneakAttackMasterySelf5
SneakAttackMasterySelf1[5]: (5872) SneakAttackMasteryOther6 =&gt; (5880) - SneakAttackMasterySelf6

MissileSpells:

SneakAttackMasterySelf1[0]: (5867) SneakAttackMasteryOther1 =&gt; (5875) - SneakAttackMasterySelf1
SneakAttackMasterySelf1[1]: (5868) SneakAttackMasteryOther2 =&gt; (5876) - SneakAttackMasterySelf2
SneakAttackMasterySelf1[2]: (5869) SneakAttackMasteryOther3 =&gt; (5877) - SneakAttackMasterySelf3
SneakAttackMasterySelf1[3]: (5870) SneakAttackMasteryOther4 =&gt; (5878) - SneakAttackMasterySelf4
SneakAttackMasterySelf1[4]: (5871) SneakAttackMasteryOther5 =&gt; (5879) - SneakAttackMasterySelf5
SneakAttackMasterySelf1[5]: (5872) SneakAttackMasteryOther6 =&gt; (5880) - SneakAttackMasterySelf6

ArmorCantrips:

CantripDirtyFightingProwess1[0]: (5882) SneakAttackMasterySelf8 =&gt; (5883) - CantripDirtyFightingProwess1
CANTRIPAXEAPTITUDE1[0]: (2557) CANTRIPMACEAPTITUDE1 =&gt; (2539) - CANTRIPAXEAPTITUDE1
CANTRIPAXEAPTITUDE1[1]: (2522) CANTRIPMACEAPTITUDE2 =&gt; (2504) - CANTRIPAXEAPTITUDE2
CantripSalvaging1[0]: (3809) CantripSalvagingMinor =&gt; (3833) - CantripSalvaging1
CANTRIPSLASHINGWARD1[2]: (3957) SlashingWard =&gt; (4678) - CANTRIPSLASHINGWARD3
CANTRIPPIERCINGWARD1[2]: (3956) PiercingWard =&gt; (4677) - CANTRIPPIERCINGWARD3

JewelryCantrips:

CantripDirtyFightingProwess1[0]: (5882) SneakAttackMasterySelf8 =&gt; (5883) - CantripDirtyFightingProwess1
CANTRIPAXEAPTITUDE1[0]: (2557) CANTRIPMACEAPTITUDE1 =&gt; (2539) - CANTRIPAXEAPTITUDE1
CANTRIPAXEAPTITUDE1[1]: (2522) CANTRIPMACEAPTITUDE2 =&gt; (2504) - CANTRIPAXEAPTITUDE2
CantripSalvaging1[0]: (3809) CantripSalvagingMinor =&gt; (3833) - CantripSalvaging1
CANTRIPPIERCINGWARD1[2]: (3956) PiercingWard =&gt; (4677) - CANTRIPPIERCINGWARD3

WandCantrips:

CantripHermeticLink1[2]: (4686) CANTRIPAXEAPTITUDE3 =&gt; (6086) - CantripHermeticLink3

MeleeCantrips:

CantripDirtyFightingProwess1[0]: (5882) SneakAttackMasterySelf8 =&gt; (5883) - CantripDirtyFightingProwess1

MissileCantrips:

CantripDirtyFightingProwess1[0]: (5882) SneakAttackMasterySelf8 =&gt; (5883) - CantripDirtyFightingProwess1

### CODE REVIEW

**Comment by gmriggs** [comment]
Requesting review from @ziang4891

**Comment by gmriggs** [comment]
Notes:

Finding some inconsistencies between the usage of AxeMastery and MaceMastery

Both seem to be linked to LightWeaponsMastery... testing in-game, and I correctly get the Light Weapons bonus from the level 7 version of both of these creature spells.

However, the standard for LightWeapons conversion has seemed to be Axe instead of Mace, so normalizing to this

**Comment by ziang4891** [comment]
Yeah, multiple, differing original spells were changed to Light Weapons mastery, possibly so Turbine didn't have to touch an item to change its spell from weapon type to class, during the MoA conversion.  Instead of redoing the item, they changed the spell that was attached.

**Comment by gmriggs** [comment]
In GemCreatureSpellMatrix, there was a column split between MaceMastery for 1-6, and TwoHandedMastery for 7-8

I'm assuming this column should be TwoHandedMastery, as there is no other column for it, and MaceMastery would have the unintended effect of doubling the chances for LightWeaponMastery

**Comment by ziang4891** [comment]
I concur with your assessment

**Comment by gmriggs** [comment]
Another thing I noticed is that for level 7-8 of salvaging buff, it switched over from Arcanum Salvaging to Nuhmudira's Wisdom

Not sure which it should be

**Pull request merged**
