### PR TITLE
Switch delayed LogOut_Inner due to PKLogoutActive to PlayerManager.Tick

### PR DESCRIPTION
**Pull request by LtRipley36706**

### CODE REVIEW

**Comment by Mag-nus** [comment]
Instead, should log out be delayed until the player is back on a landblock?

**Comment by gmriggs** [comment]
> Instead, should log out be delayed until the player is back on a landblock?

They never return to the landblock... that's the bug

CurrentLandblock is somehow going null for the player, even though the Landblock.worldObjects list still contains references to the player

**Comment by Mag-nus** [comment]
I'm still thinking that this should be a function of the Session, not PlayerManager.

**Comment by LtRipley36706** [comment]
Doesn't matter where it is, as long as it can't go null and can tick without being "in game" to completion

**Pull request merged**
