### PR TITLE
/serverperformance command (Server Performance Monitor)

### PR DESCRIPTION
**Pull request by Mag-nus**
Optional parameters are:
start
stop
reset

If no parameters are present, the current performance metrics are spit out.

When disabled, overhead is the cost of some simple function calls and a bool check. When enabled, the additional cost is stopwatch events. In comparisson to the work that ACE does for normal processing, the work done when serverperformance is enabled is nearly 0.

Default is disabled.

Enable it to start up automatically in the config.js. This is recommend for most servers. Enable it at runtime using /serverperformance start

### CODE REVIEW

**Comment by fartwhif** [comment]
`ACE.Plugin.Web` and `ACE.Plugin.API` will have [support for websockets](https://github.com/NancyFx/Nancy/wiki/WebSockets-in-Nancy-using-OWIN) as per the "high perf/throughput data" [requirement](https://github.com/ACEmulator/ACE/issues/718#issuecomment-399276239), and this would be an ideal use with it.  This is semi-related to [the need for this generalization of the /serverstatus admin command](https://github.com/ACEmulator/ACE/pull/1629/files) so that outside utilities can also use it.  I haven't yet had the chance to review this, but just in case I'm asking that this also be "plugin-aware" so that the output can be funneled into another process, by use of event, action, etc.  Make its consumption generalized so that it can be used outside of the normal console+in game chat method.

**Comment by Mag-nus** [comment]
fartwhif, It is written in a way that will allow plugin consumption.

ServerPerformanceMonitor is a public static class.
It exposes simple functions to Start/Stop/Reset.
It exposes a public ToString()
It also exposes public ways to get specific monitors.

I don't know how the plugins interact with the system yet, but, if they can access any of the static manager classes easily, then they will be able to control and get data from this resource.

**Comment by fartwhif** [comment]
Nice, that's good to hear.  Is there any way to have some kind of "streaming" mode, so that whenever the state changes that the new attribute, or the whole thing, is then sent to all event subscribers?  `OnChange?.Invoke(this);`

**Comment by Mag-nus** [comment]
That woudldn't work for an object like this. The overhead would be immense.

This manager can be called tends of thousands of times a second. It's written in a very basic way to maximize performance at the expense of a little readability.

**Comment by fartwhif** [comment]
I see, so a wrapper that polls it would be in order.  Was worth asking.  Thanks!

**Pull request merged**
