### PR TITLE
Step 1. Add new adapter classes and models

### PR DESCRIPTION
**Pull request by Mag-nus**
All classes and objects added are in new namespaces.

This add has 0 interraction on existing ACE code.

This sets the groundwork for Step 2. Moving World DB caching to the new models

### CODE REVIEW

**Comment by Mag-nus** [comment]
It was just an easy way to go from what we have to the model system.

If you'd like the names changed, please suggest new names in the following format (or similar)
OldName -> NewName

**Comment by gmriggs** [comment]
my suggestion is that only the things that are actually properties in ac should be listed as properties:

https://acemulator.github.io/protocol/Types/ACBaseQualities.html

ie., all the PropertyTypes, where types are primitive types

EnchantmentRegistry it not a property. it should be just EnchantmentRegistry, not PropertyEnchantmentRegistry

**Comment by gmriggs** [comment]
technically it shouldn't even be ICollection<EnchantmentRegistry>, it should be ICollection<Enchantment>

**Comment by Mag-nus** [comment]
This needs to be thought through more.

You'll end up with some properties that become BodyPart, Emotes (EmoteSet -> Emote), AnimPart (which already has a simliar named AnimData in entity)...

And then you get to things like Attribute and Attribute2nd, Skill, etc.. where if you remove the Properties prefix, you can get collisions with other enums or entity objects that are similar, but not the same.

I would suggest waiting to switch the names and/or theme of the names until after this is all pushed into master.

Trying to switch the names now adds another layer of confusion and room for error.

**Pull request merged**
