### PR TITLE
session termination and boot command enhancement

### PR DESCRIPTION
**Pull request by fartwhif**
- added base system needed for more involved graceful session termination
- centralized termination reasons
- command parameter parsing tooling/framework, will make it easier to continue work, especially for implementation of graceful in-world account boot.
- added optional reason parameter to boot command

### CODE REVIEW

**Comment by Mag-nus** [comment]
Can you please separate these features into individual PR's so they can be reviewed individually?

**Comment by fartwhif** [comment]
These items are so well related.  What part of it should be separate?

Also, the added complexity paves the road for more intricate scenarios like the graceful boot operation that @gmriggs and I figured out the other day.  There's a conversation server and client are supposed to have after the AccountBoot message is sent.  search the PCAPS for the operation code F7DC to find relevant retail activity

**Comment by Mag-nus** [comment]
Well, this looks like it should be two RP's:
Command Parameter Parsing
Network Session Stuff

**Comment by fartwhif** [comment]
As agreed in chat I'll try and keep my PRs more separate.

**Comment by fartwhif** [comment]
there's an undocumented bug allowing for `boot axe man char` without the comma

**Pull request merged**
