### PR TITLE
Change password hashing to use scrypt

### PR DESCRIPTION
**Pull request by zbuc**
I switched the password hashing over to use libsodium's scrypt
implementation. This involved adding a new migration.

I noticed that currently the password isn't checked. I started looking
into how to implement password checking and it looks like we will
probably need to have a launcher to do so.

The reason the commit touches so many files is because it also cleans up
the files with mixed line endings.

### CODE REVIEW

**Comment by zbuc** [comment]
Fixes Issue #15

**Comment by Mag-nus** [comment]
I like the idea, but, i don't feel it's necessary to visit until we know how account create will actually work.

Merging it into current though seems fine. Probably better sooner rather than later as I assume accounts will have to be recreated.

**Comment by Thwargle** [comment]
Technically; we DO have a launcher. I will work with whoever necessary to implement this into the launcher when ready. It's currently stable and fully featured as far as i can tell; so it's at a stage where implementing true password passing between server and client launch is reasonable.

**Comment by Mogwai-AC** [comment]
closing due to being outdated plus inability to merge.

**Pull request closed without merging**
