### PR TITLE
Landblocks

### PR DESCRIPTION
**Pull request by lurker-mcdoogle**
there are a lot of // TODO comments all over this thing.

here's what I know works:
/telepoi town1
/createlifestone
/telepoi town2
/telepoi town1
... and the lifestone is still there.

Looked like Mogwai bailed yesterday so I figured I'd upload this stuff just in case you wanted it.

Local chat was started, but not done.  I may or may not have broken it - I didn't test.

### CODE REVIEW

**Comment by lurker-mcdoogle** [comment]
Hrm, noticed some bugs around objects not getting into the landblock collection. Not mergeworthy yet, but feel free to comment.

**Comment by Mag-nus** [comment]
Is this a modified version of mogwais code?

**Comment by lurker-mcdoogle** [comment]
no, he was talking about event systems of some sort.

**Comment by lurker-mcdoogle** [comment]
Updated with:
1) basic object factories
2) log4net - not having console output was killing me and we needed a logging framework anyway.  nuget to the rescue.
3) moved "in front of" calculations to hang off the Position object for better reuse
4) fixed various landblock object cache bugs
5) added even more // TODO

**Comment by Mag-nus** [comment]
Ahh ok. I'll have to review this today.

Talking with mogwai in private, his initial plan was event based, but it didn't pan out, so he scrapped that and was working on a different system, so I wasn't sure if this was that.

**Comment by Mag-nus** [comment]
I loaded this up. Broadcasting works which is nice. Seems to be a bit of client and server instability issues though. Will have to look at it more in depth.

Also, it would be cleaner to review if the log4net changes weren't combined with the landblock code. Landblock management is already complex enough.

**Comment by lurker-mcdoogle** [comment]
I can gut the log4net stuff if you want, but I couldn't have debugged this without it.  Either way.  And yeah, I had stability issues as well, but it wasn't anything consistently reproducible.  There was a comment about the update having to be sent after the client entered portal space, but I didn't do anything explicit to account for it.

Let me know if you find anything specific.

**Comment by Mag-nus** [comment]
At this point, might as well keep the log4net in there. It makes sense moving forward, and no sense in duplicating the work later.

**Comment by lurker-mcdoogle** [comment]
Merge conflicts now.  Closing - will rebase when i can.

**Pull request closed without merging**
